version: "3.8"
services:

  frontend:
    image: sit-careers:dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-dev
    working_dir: /app
    container_name: sit-careers-fe
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - sit-careers

  fe-nginx:
    image: nginx:1.19.4-alpine
    working_dir: /etc/nginx
    container_name: sit-careers-fe-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/frontend-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sit-careers

networks:
  sit-careers:
    driver: bridge
